[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-apple-darwin]
# Esse "-Wl,-x" diz pro linker do Mac: "Apaga os símbolos locais, parça!"
rustflags = ["-C", "link-arg=-Wl,-x"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-x"]
